######################################################################
# Automatically generated by qmake (2.01a) mar. févr. 12 17:34:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h simulator.h ../protocol.h
SOURCES += main.cpp simulator.cpp
