######################################################################
# Automatically generated by qmake (2.01a) mar. févr. 12 17:34:39 2013
######################################################################

TEMPLATE = app
TARGET = gui
VPATH += ../protocol/
INCLUDEPATH += $$VPATH
QT += core gui network
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += main.h simulator.h protocol.h
SOURCES += main.cpp simulator.cpp
